#! /bin/bash

#variáveis
varDate=$(date)
varMessageDef="commit automático jean - data: $varDate"
varDir=$(pwd)
branch=$(git branch | grep \* | cut -f2 -d ' ')
branchesList="";

for i in $(git branch)
do
	#testa se o retorno é um arquivo
	if [ -e $i ]
	then
		continue
	fi


	if [ -z $branchesList ]
	then
		branchesList=$i
	else
		branchesList=$branchesList:$i
	fi
done;

#end variáveis

read -p "Branch padrão <$branch>, para sobreescrever digite seu nome. Branches atualmente disponíveis <$branchesList>" newBranch

if [[ $newBranch ]] 
then
	branch=$newBranch
fi

echo "Efetuando pull, diretório atual: $varDir "
git pull origin $branch

echo "Efetuando o add . " 
git add . 

# pega a mensagem do commit do usuário
read -p "mensagem do commit default <$varMessageDef>" varMessage

if [[ ! $varMessage ]]; then
    varMessage=$varMessageDef
fi

git commit -m "$varMessage" -a


echo "fazendo o push"
#pega o branch do commit 

git push origin $branch

