#! /bin/bash

# rotina de automatização dos casos mais brandos
# de versionamento com git


now=$(date)
defaultMessage="mensagem automática jean - $now"
dir=$(pwd)
branch=$(git branch | grep \* | cut -f2 -d ' ')
branchesList="";

for i in $(git branch)
do
	#testa se o retorno é um arquivo
	if [ -e $i ]
	then
		continue
	fi


	if [ -z $branchesList ]
	then
		branchesList=$i
	else
		branchesList=$branchesList:$i
	fi
done;


read -p "Branch padrão <$branch>, para sobreescrever digite seu nome. Branches atualmente disponíveis <$branchesList>" newBranch

if [[ $newBranch ]] 
then
	branch=$newBranch
fi


echo "Efetuando pull, diretório atual: $dir "

git pull origin $branch 

if [ $# ]
then
	echo "Pull efetuado com sucesso!"
else
	echo "Algum erro aconteceu durante o pull, provavelmente a conexão ao servidor está inalcançável"
	exit 1
fi

echo "Efetuando o add . " 
git add . 

# pega a mensagem do commit do usuário
read -p "mensagem do commit default <$defaultMessage>" newMessage

#se a nova mensagem não foi setada
#a nova mensagem será a mensagem padrão
if [[ ! $newMessage ]]
then
    newMessage=$defaultMessage
fi

#commita as modificação com a mensagem
#especificada
git commit -m "$newMessage" -a

echo "Efetuando o push"
if  $(git push origin $branch 2> /dev/null) 
then
	echo "Push efetuado com sucesso!"
else
	echo "Algum erro aconteceu, provavelmente a conexão ao servidor está inalcançável"
	exit 1
fi
