#!/usr/bin/zsh

FILES_DIR=/home/jean/projects/wiki/src

remove_empty_line() {
      sed '/^$/d'
}

content=$(grep -RPzoh "\n\*{3}[^\*]+\*{3}" $FILES_DIR/**/*.md 2>/dev/null | tr "\*\*\*" "\n" )

[ -f /tmp/wiki_highlights  ] && {
    rm -rf /tmp/wiki_highlights
}
echo "$content" |  remove_empty_line | sed "s/\x00/|/" | sed 's/|[\n\t\x00]|/|/'>  /tmp/wiki_highlights


IFS="|"
total_highlights=0
for i in $(cat /tmp/wiki_highlights)
do
    if [ -z $i ] || [[ $(wc -c <<< "$i")  -le 3 ]]
    then
        continue
    fi

    total_highlights=$(( $total_highlights + 1 ))
done
show_index=$(./random 0 $total_highlights)

counter=0
for i in $(cat /tmp/wiki_highlights)
do
    if [[ -z $i ]] || [[ $(wc -c <<<  "$i")  -le 3 ]]
    then
        continue
    fi

    if [ $counter -eq $show_index ]
    then
        echo "$i"
    fi
    counter=$(( $counter + 1 ))
done

