#!/bin/bash

random_value=$(./random 0 100)
if [ $random_value  -le 25 ]
then
     echo "$(./quote_random)"
elif [ $random_value -le 50 ]
then
    echo "$(./glossary_random)"
elif [ $random_value -le 75 ]
then
    echo "$(./highlight_wiki_random)"
else
    echo "$(./remember_random)"
fi
